services:

  api:
    container_name: api
    build:
        context: ./
        dockerfile: ./Dockerfile.java
    ports:
      - '8080:8080'
    networks:
      - desafio_votacao
    depends_on:
      - postgres
    restart: always
    stdin_open: true
    tty: true

  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: sistema_votacao
      POSTGRES_PASSWORD: uj9Gi7Pw8DiMoxn
      POSTGRES_DB: db_server
    volumes:
      - "pg_data:/var/lib/postgresql/data"
      - ./.scripts/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - desafio_votacao
    restart: always
    stdin_open: true
    tty: true

  locust:
    image: locustio/locust
    container_name: locust
    ports:
      - "8089:8089"
    networks:
      - desafio_votacao
    volumes:
      - ./.locust:/mnt/locust
    command: >
      -f /mnt/locust/locustfile.py
      --host http://api:8080/desafio-votacao
    depends_on:
      - api

volumes:
  pg_data:

networks:
  desafio_votacao:
    driver: bridge
