INSERT INTO GOVERNANCA.PAUTA (ASSUNTO, DT_HR_INCLUSAO)
VALUES ('A favor do retorno do horário de verão', CURRENT_TIMESTAMP);

INSERT INTO GOVERNANCA.SESSAO_VOTACAO (ID_PAUTA, DT_HR_ENCERRAMENTO, DT_HR_INCLUSAO)
VALUES (1, (date_trunc('month', CURRENT_TIMESTAMP) + interval '1 month - 1 day'), CURRENT_TIMESTAMP);